# Generated by Django 4.1.2 on 2023-11-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
